# This program demonstrates simple usage of the match function
# for evaluating an abstract syntax tree that adds two numbers together.
#
# To run this script, install the "coffee" command line, then run "coffee tests.coffee"
#
# Curran Kelleher
# December 2014
match = require "./dist/match"

# An abstract syntax tree data structure that adds two numbers together.
# A structure like this can be generated by a parser for a domain specific language.
tree =
  type: "add"
  left:
    type: "number"
    value: 3
  right:
    type: "number"
    value: 4

# This function evaluates the abstract syntax tree,
# using the match function to apply different evaluation functions
# depending on the type of the node.
evalTree = match "type",
  add: (node) -> (evalTree node.left) + (evalTree node.right)
  number: (node) -> node.value

# Run the function.
# Prints "3 + 4 = 7"
console.log "3 + 4 = #{evalTree tree}"
